on:
  push:
    branches:
      - main

concurrency: "releases"

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: github-release
          release-type: node
          package-name: my-package
          default-branch: main

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: next
      - name: rebase next onto main
        run: |
          git fetch origin
          git checkout -b main origin/main
          git checkout next
          git rebase main
          git push --force-with-lease origin next
